# ~/.cloudflared/config.yml
tunnel: spotifyrpc-api
credentials-file: /home/user/.cloudflared/id.json

ingress:
  - hostname: spotifyrpc.example.com
    service: http://localhost:8000
  - service: http_status:404
